CC=javac

# The target
all: Server.class Client.class

# To generate the class files
Server.class: Server.java
	$(CC) Server.java

Client.class: Client.java
	$(CC) Client.java

# clean out the dross
clean:
	-rm *.class
